### ISSUE TITLE
Дублирующиеся файлы и код

### ISSUE THREAD

**Issue by i582** [Rudovich1/Cpm-Compiler#3]
Привет!
Я проверяю твое тестовое задание в команду KPHP. Смотря на структуру проекта, я честно не понимаю что из этого что. Дублирующиеся файлы, файлы на 1500 строк, которые такое чувство что являются склейкой всех других. Пожалуйста, оставь только те файлы, которые нужны, так как в текущем варианте проверять это задание очень трудно.

**Comment by Rudovich1** [comment]
Привет,
Все исправил.

**Comment by i582** [comment]
@Rudovich1 Так уже лучше, но подскажи, в чем сакральный смысл склеивать файлы в один нечитаемый файл на 1500 строк?

**Comment by i582** [comment]
Также подскажи где ты собираешь проект? Просто у тебя в репозитории нет ни Makefile, ни CMake? И еще, поправь пожалуйста форматирование, например, в файле [cpm_compiler.cpp](https://github.com/Rudovich1/Cpm-Compiler/blob/master/files/cpm_compiler.cpp), в текущем виде смотреть это очень сложно.

**Comment by Rudovich1** [comment]
Собираю в VS, просто в гит решил загрузить только код, сейчас поправил. Склеивал файлы в один, чтобы тестировать проще было.
